name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animated_theme_switcher: ^2.0.8
  animations: ^2.0.8
  audio_video_progress_bar: ^2.0.0
  audioplayers: ^5.1.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_mobx: ^2.0.6+5
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  http: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  intl_phone_field: ^3.2.0
  lottie: ^2.6.0
  mobx: ^2.2.0
  pinput: ^3.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  stripe_checkout: ^1.0.2
  table_calendar: ^3.1.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: null

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: null
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/icons/
    - assets/images/pokemons_types/
    - assets/images/technical_records_types/
    - assets/images/technical_machines_types/
    - assets/images/pokemons_generations/generation_1/
    - assets/images/pokemons_generations/generation_2/
    - assets/images/pokemons_generations/generation_3/
    - assets/images/pokemons_generations/generation_4/
    - assets/images/pokemons_generations/generation_5/
    - assets/images/pokemons_generations/generation_6/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_8/
    - assets/lotties/
    - assets/images/pokemons_types/20/water.png
